name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This job is named 'test' for clarity
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Node.js version
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      # Step 3: Install dependencies securely and quickly
      - name: Install dependencies
        run: npm ci

      # Step 4: Run your tests
      - name: Run tests
        run: npm test
